name: Package and Deploy
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Load the repo
        uses: actions/checkout@v4

      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: shrugging/react-app:latest
