on: push

jobs:
  npm-build:
    name: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Load the repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Package project
        run: npm run build
